Flex visualizer
HaohanWang/Robustar_implementation pull request #59
Opened 2022-09-18 14:52 UTC by monmonli

Model focus cannot scroll in dev branch

2022-09-25 14:16 UTC, PaulCCCCCCH requested changes
Thanks for the PR. Left a few comments

2022-09-25 14:16 UTC, PaulCCCCCCH commented on front-end/package.json
> +    "less-loader": "^7.3.0",
Why are `less` and `less-loader` required for this PR?
Try not to import new libraries unless it's necessary.

2022-09-25 14:16 UTC, PaulCCCCCCH commented on front-end/packages/robustar/src/components/prediction-viewer/Visualizer.vue
> +          <div style="overflow-y: scroll; height: 100%; width: 400px">
Try to use `vh` and `vw` instead of `px` in this block

2022-09-25 14:16 UTC, PaulCCCCCCH commented on package-lock.json
>  {
If you are not introducing new packages or updating package versions, please revert the changes in `package-lock.json`. `npm install` may mutate this file and creates a lot of unnecessary changes.

2022-09-25 14:16 UTC, PaulCCCCCCH commented on package.json
> +    "less": "^4.1.3"
Again, please consider removing `less` if it's not necessary.

2022-10-02 10:13 UTC, monmonli commented
Sorry for my late reply. I merged this branch with dev and eliminate the less packages. I also modified the use of 'px's and found that there is no need to use units. Could you review the files again? Thank you

2022-10-02 20:45 UTC, monmonli commented
Hi I finally get rid of the less packages. Could you check on them?

2022-10-08 04:53 UTC, PaulCCCCCCH approved these changes

2022-10-08 04:53 UTC, merged